apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cron-cam-contact-services-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/getSweetSpotcl/infra-apps.git'
    targetRevision: HEAD
    path: apps/cron-cam-contact-services/overlays/qa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true