apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-cam-contact-services
spec:
  selector:
    matchLabels:
      app: cron-cam-contact-services
  template:
    metadata:
      labels:
        app: cron-cam-contact-services
    
          