apiVersion: v1
kind: Service
metadata:
  name: cron-cam-contact-services-service
spec:
  selector:
    app: cron-cam-contact-services
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080