apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cam-contact-services
spec:
  schedule: "*/5 * * * *"  # Ejecutar cada 1 minuto
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 2
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-login-secret
          containers:
            - name: cron-cam-contact-services
              image: ghcr.io/getsweetspotcl/cron-cam-contact-services:v0.1.0
              env:
              - name: DB_URI
                valueFrom:
                  secretKeyRef:
                    name: sec-k8-campaigns-cron-launch
                    key: DB_URI
          restartPolicy: Never